hash-format = "sha256"

[[files]]
file = "mods/appleskin.toml"
hash = "1771ee6311c039866a657ede4cd6bc4e7e7044095ba32283c7cfd704600e5e55"
metafile = true

[[files]]
file = "mods/aquaculture.toml"
hash = "86d2ccabf5b6e5eb9011d882f75a1f66f04321b5dad3d20f74f9d21f6f604c30"
metafile = true

[[files]]
file = "mods/architectury-forge.toml"
hash = "17d57c2af22efc07ebb7f6ac52d1f6c2b7d2e5c1b74c0508cd5f03e9c8929cb5"
metafile = true

[[files]]
file = "mods/autoreglib.toml"
hash = "a60b5c5335fc13690a73fd713dbe1f47da377e7f1a61b5351e2b518b754c70d1"
metafile = true

[[files]]
file = "mods/bad-wither-no-cookie-reloaded.toml"
hash = "d3ddbad2ec35929221831670f5a16e4d159fef0e99c783ce9ceb8cd309a1be27"
metafile = true

[[files]]
file = "mods/bookshelf.toml"
hash = "994889c36ee37d4abfcb7ccaef54320837b5bfe8337f44764f100ef418aa3701"
metafile = true

[[files]]
file = "mods/botany-pots.toml"
hash = "31428820b7c0c06808005457968a2ca4175d60bceae95b913ba53f7ef576f44d"
metafile = true

[[files]]
file = "mods/botany-trees.toml"
hash = "3eb44f6ec92da1c51c5890a7e75ebf04c46f4d4e12831a440c3c92c693d3de8d"
metafile = true

[[files]]
file = "mods/chisel.toml"
hash = "33460c3e11632442415f328eb6f56d9803c9815b876b57138305de2595b6a2f2"
metafile = true

[[files]]
file = "mods/chisels-bits.toml"
hash = "e3a655e225c87b358638d7f443f939cebdd02f317554a3b912ed6c80b0253140"
metafile = true

[[files]]
file = "mods/configured.toml"
hash = "1cafb358ea8a10bf8947b46f101117b4fa04af9d946296d7d90453818df2776d"
metafile = true

[[files]]
file = "mods/controlling.toml"
hash = "55c39db77fbd539d4254a8e05016704bedfcd9a1f58694292d25a260c41b761d"
metafile = true

[[files]]
file = "mods/cooking-for-blockheads.toml"
hash = "d8a178cdaa583440c4a5912682b1e62127f207dfb62b5e58c4be3126032b76b8"
metafile = true

[[files]]
file = "mods/cosmetic-armor-reworked.toml"
hash = "baa2365621616fab956515cb480029fc3d86412f541de094b1cbf65270d04cdf"
metafile = true

[[files]]
file = "mods/ctm.toml"
hash = "96952a151cc5f530bf7732f8031f66300cd8fca5241570cb8704d8628c4722b5"
metafile = true

[[files]]
file = "mods/ding.toml"
hash = "58caf5a237175353871935ce4602681918fa8190ae418a30272b416f41858707"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.toml"
hash = "46e3274bd7b7f0db81e055c0507de55fa7eb839181543ddda90794d13da02e1c"
metafile = true

[[files]]
file = "mods/essentials.toml"
hash = "c9fbfb31a0d9d012e44875db61d155e6177b565a040b5f63fe85268aeeef4a5d"
metafile = true

[[files]]
file = "mods/fastfurnace-minus-replacement.toml"
hash = "9521a8997c457923249866a8032859028f41ca9dd0364f261bd7c7b5823e1383"
metafile = true

[[files]]
file = "mods/ftb-backups-forge.toml"
hash = "2c074746ddf0d4d4043ffa534ce50f1d95b0c3b6f2e3339dcfa87864c08d2fd8"
metafile = true

[[files]]
file = "mods/ftb-chunks-forge.toml"
hash = "3421e9d426327c7e8dd9bbffa30e804c453ed54d93353f077b8082bb27cec3a4"
metafile = true

[[files]]
file = "mods/ftb-library-forge.toml"
hash = "e93b9ba5f9b8b14ca783302a64d61f987b3e7548f6460df76899e5aea41faccc"
metafile = true

[[files]]
file = "mods/ftb-teams-forge.toml"
hash = "ab454689e506308546d7a1b020137d187714b5d7fb841d0d8c1c5dbcb8d659b6"
metafile = true

[[files]]
file = "mods/iron-chests.toml"
hash = "09aea63e302183fd68dcb4c58e6bca09e10b90107131b404d9668a4f4165c41d"
metafile = true

[[files]]
file = "mods/jei-integration.toml"
hash = "b355744b4751322e467c8d92d375f228fce27a8b5b8dae3b05afc435ff4434dd"
metafile = true

[[files]]
file = "mods/jei.toml"
hash = "3f8803ed3daea9508f4617adc6435597f18df2d5ba8878951ebbbbdc841d9e61"
metafile = true

[[files]]
file = "mods/journeymap.toml"
hash = "6726739845c430ae94de62e97600dfc778a68b3ed80daeb927cab8e04898bd30"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.toml"
hash = "c5eaa726d17c8c45245ecc4a6ad63d48276b137f8e960f3684c6fb7921793929"
metafile = true

[[files]]
file = "mods/mod-name-tooltip.toml"
hash = "a0c6f8cba016df71eca9fbb9c8ab0f4ec6a88784ba1b13522bc5f365e6262765"
metafile = true

[[files]]
file = "mods/mouse-tweaks.toml"
hash = "466641af19e51e3514a6926c2eb91107cb52b8ce2200fe732974c80ed455d0b4"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-crops.toml"
hash = "9bd410fba71c16b9483619cdd5a600e4307b88860b5490d6ec5fdbbf440cac6f"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-food-core.toml"
hash = "78ee581217d324aafd9a615147e3ccf9657cf7477cea95b4a4bb4da394e29bfd"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-food-extended.toml"
hash = "7ecc80279460f32c03ce6c4e15226d0ce6635ae19a06ac93242a514348f15d55"
metafile = true

[[files]]
file = "mods/pams-harvestcraft-2-trees.toml"
hash = "293c5b521f1a348c51063167a568dcb34ee5de4957d4399b5a609232bc14722e"
metafile = true

[[files]]
file = "mods/quark.toml"
hash = "ee49ae892b8d1483172b2132f30b96a3ba45d2d46ba51a2113e0aee3eb90c909"
metafile = true

[[files]]
file = "mods/randompatches-forge.toml"
hash = "8f72255793f7ddef6a2c773cdb2fffa0ab5947f47c97a42de51f5795a3a2776a"
metafile = true

[[files]]
file = "mods/super-saturation.toml"
hash = "9744d0c180f3a5f6d926810fcc12748cf7dc9e54f70e51ef81ed557e19b93a7b"
metafile = true

[[files]]
file = "mods/the-one-probe.toml"
hash = "f4e6938e8f10191a39b594c1910f66f80fb17366131f68706ce89a0559e274f8"
metafile = true

[[files]]
file = "mods/time-in-a-bottle-standalone.toml"
hash = "4e721bced34a7786280ac12ad80e68e00900522e9bf749945b35b92de8ec2212"
metafile = true

[[files]]
file = "mods/tipthescales.toml"
hash = "d3cf8388084a05c6fa9dba93d865316c935d7891d598c32e3d4079a718db8008"
metafile = true

[[files]]
file = "mods/top-addons.toml"
hash = "3a5f59b8930840994d81bf04ce3ba66c40a19e7d4c23d8cc7e269afd4203035c"
metafile = true

[[files]]
file = "mods/uppers.toml"
hash = "0a17bba2e6fff558dc4a761222b2a43c0b34a3f01ba2f699d1fff747c7506a72"
metafile = true
